# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_ScrapeGoogle(object):
    def setupUi(self, ScrapeGoogle):
        ScrapeGoogle.setObjectName("ScrapeGoogle")
        ScrapeGoogle.resize(583, 679)
        self.horizontalLayoutWidget = QtWidgets.QWidget(ScrapeGoogle)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 10, 491, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.productLbl = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.productLbl.setFont(font)
        self.productLbl.setObjectName("productLbl")
        self.horizontalLayout.addWidget(self.productLbl)
        self.productText = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.productText.setFont(font)
        self.productText.setObjectName("productText")
        self.horizontalLayout.addWidget(self.productText)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(ScrapeGoogle)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 50, 491, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rateLbl = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.rateLbl.setFont(font)
        self.rateLbl.setObjectName("rateLbl")
        self.horizontalLayout_2.addWidget(self.rateLbl)
        self.rateText = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.rateText.setFont(font)
        self.rateText.setObjectName("rateText")
        self.horizontalLayout_2.addWidget(self.rateText)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(ScrapeGoogle)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(50, 100, 491, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.googleURLLbl = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.googleURLLbl.setFont(font)
        self.googleURLLbl.setObjectName("googleURLLbl")
        self.horizontalLayout_3.addWidget(self.googleURLLbl)
        self.googleURLText = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.googleURLText.setFont(font)
        self.googleURLText.setObjectName("googleURLText")
        self.horizontalLayout_3.addWidget(self.googleURLText)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(ScrapeGoogle)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(50, 150, 491, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.amazonURLLbl = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.amazonURLLbl.setFont(font)
        self.amazonURLLbl.setObjectName("amazonURLLbl")
        self.horizontalLayout_4.addWidget(self.amazonURLLbl)
        self.amazonURLText = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.amazonURLText.setFont(font)
        self.amazonURLText.setObjectName("amazonURLText")
        self.horizontalLayout_4.addWidget(self.amazonURLText)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(ScrapeGoogle)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(50, 200, 491, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.intervalLbl = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.intervalLbl.setFont(font)
        self.intervalLbl.setObjectName("intervalLbl")
        self.horizontalLayout_5.addWidget(self.intervalLbl)
        self.intervalText = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.intervalText.setFont(font)
        self.intervalText.setObjectName("intervalText")
        self.horizontalLayout_5.addWidget(self.intervalText)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(ScrapeGoogle)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(50, 240, 491, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.resultLbl = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.resultLbl.setFont(font)
        self.resultLbl.setObjectName("resultLbl")
        self.horizontalLayout_6.addWidget(self.resultLbl)
        self.resultText = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.resultText.setFont(font)
        self.resultText.setObjectName("resultText")
        self.horizontalLayout_6.addWidget(self.resultText)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(ScrapeGoogle)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(50, 280, 491, 341))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.runStateLbl = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.runStateLbl.setFont(font)
        self.runStateLbl.setObjectName("runStateLbl")
        QtWidgets.QApplication.processEvents()
        self.horizontalLayout_7.addWidget(self.runStateLbl)
        self.stateText = QtWidgets.QTextEdit(self.horizontalLayoutWidget_7)
        self.stateText.setObjectName("stateText")

        # 下面将输出重定向到textEdit中
        # sys.stdout = EmittingStream(textWritten=self.outputWritten)
        # sys.stderr = EmittingStream(textWritten=self.outputWritten)
        # 接收信号str的信号槽

        self.horizontalLayout_7.addWidget(self.stateText)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(ScrapeGoogle)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(50, 620, 491, 80))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.saveDataBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.saveDataBtn.setFont(font)
        self.saveDataBtn.setObjectName("saveDataBtn")
        self.horizontalLayout_8.addWidget(self.saveDataBtn)
        self.openResultFileBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.openResultFileBtn.setFont(font)
        self.openResultFileBtn.setObjectName("openResultFileBtn")
        self.horizontalLayout_8.addWidget(self.openResultFileBtn)
        self.runBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.runBtn.setFont(font)
        self.runBtn.setObjectName("runBtn")
        self.horizontalLayout_8.addWidget(self.runBtn)

        self.retranslateUi(ScrapeGoogle)
        QtCore.QMetaObject.connectSlotsByName(ScrapeGoogle)


    def outputWritten(self, text):
        cursor = self.stateText.textCursor()
        cursor.movePosition(QtGui.QTextCursor.End)
        cursor.insertText(text)
        self.stateText.setTextCursor(cursor)
        self.stateText.ensureCursorVisible()


    def retranslateUi(self, ScrapeGoogle):
        _translate = QtCore.QCoreApplication.translate
        ScrapeGoogle.setWindowTitle(_translate("ScrapeGoogle", "ScrapeGoogle"))
        self.productLbl.setText(_translate("ScrapeGoogle", "产品名称:"))
        self.productText.setToolTip(_translate("ScrapeGoogle", "<html><head/><body><p>请输入产品名称,多个产品之间使用逗号隔开</p></body></html>"))
        self.rateLbl.setText(_translate("ScrapeGoogle", "评         分:"))
        self.rateText.setToolTip(_translate("ScrapeGoogle", "<html><head/><body><p>请输入产品名称,多个产品之间使用逗号隔开</p></body></html>"))
        self.googleURLLbl.setText(_translate("ScrapeGoogle", "谷歌地址:"))
        self.googleURLText.setToolTip(_translate("ScrapeGoogle", "<html><head/><body><p>请输入产品名称,多个产品之间使用逗号隔开</p></body></html>"))
        self.amazonURLLbl.setText(_translate("ScrapeGoogle", "亚马逊地址:"))
        self.amazonURLText.setToolTip(_translate("ScrapeGoogle", "<html><head/><body><p>请输入产品名称,多个产品之间使用逗号隔开</p></body></html>"))
        self.intervalLbl.setText(_translate("ScrapeGoogle", "间隔时间:"))
        self.intervalText.setToolTip(_translate("ScrapeGoogle", "<html><head/><body><p>请输入产品名称,多个产品之间使用逗号隔开</p></body></html>"))
        self.resultLbl.setText(_translate("ScrapeGoogle", "结果路径:"))
        self.resultText.setToolTip(_translate("ScrapeGoogle", "<html><head/><body><p>请输入产品名称,多个产品之间使用逗号隔开</p></body></html>"))
        self.runStateLbl.setText(_translate("ScrapeGoogle", "执行状态:"))
        self.saveDataBtn.setText(_translate("ScrapeGoogle", "保存数据"))
        self.openResultFileBtn.setText(_translate("ScrapeGoogle", "打开结果文件"))
        self.runBtn.setText(_translate("ScrapeGoogle", "执行程序"))

